name: USBAccelTest
options:
  bundleIdPrefix: com.raretree
targets:
  USBAccelTest:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [USBAccelTest]
    info:
      path: USBAccelTest/Info.plist
      properties: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raretree.usbacceltest
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
