name: USBAccelTest
options:
  bundleIdPrefix: com.raretree
packages:
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    from: 1.28.0
targets:
  USBAccelTest:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [USBAccelTest]
    info:
      path: USBAccelTest/Info.plist
      properties: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raretree.usbacceltest
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    dependencies:
      - package: SwiftProtobuf
